spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=rajeswarir
spring.datasource.password=pwd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080